name: Python

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Install hashcat
      run: sudo apt install hashcat crunch
    - name: Install dependencies
      run: |
        git clone -b Test https://github.com/Biangkerok32/naive-hashcat
    - name: cd
      run: |
        cd naive-hashcat
    - name: Make Dictionary
      run: |
        sudo crunch 8 12 pass
    - name: Move Dictionary
      run: |
        mv pass dicts/
    - name: Hash running..
      run: |
        
        HASH_FILE=adil.hccapx POT_FILE=pass.pot HASH_TYPE=22000 ./naive-hashcat.sh
